---
title: "NHANES Survival Analysis -- Checking NHANES Weights First"
author: "Christine Lucille Kuryla"
date: "2025-01-08"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(survival)
```

# Load and Wrangle Data

```{r}

# Load and wrangle nhanes data 

data_nh <- read_csv(here("code_examples/kamaryn_nhanes/nhanes_1999-2018_2023-11-29.csv"))

dim(data_nh)
sum(is.na(data_nh$health)) # note there are 38579 NA's for health out of 96241 subj

year_to_wave <- read_csv(here("big_data/NHANES/nhanes_4/nh4_year_to_wave.csv")) %>% 
  mutate(release_nb = wave) 

data_nhanes <- data_nh %>% 
  filter(visit == 1) %>% 
  filter(age_visit >= 18) %>% 
  filter(!(is.na(health))) %>% # remove subjects without our primary variable of interest
 # left_join(year_to_wave, by = "release_nb") %>% # year of survey (***note each survey is two years, this is aproximate and just the first year)
  mutate(srh = 6 - health) %>%  # recode SRH to be more intuitive (Excellent = 5 to Poor = 1)
  mutate(age = age_visit) # more intuitive naming for APC analyses

# variables of interest: 
# self-rated health: "health" originally, reverse recoded to "srh"
# age at survey: "age_visit"
# age at follow-up (censored/deceased): "age_last"
# vital status at follow-up (alive/decesased): "deceased"
# year/wave: "release_nb"
# SEQN: "BaseID"
# "ddem_wghts"	Full Sample 2 Year MEC Exam Weight	WTMEC2YR
# "dem_wghts_4yr"	Full Sample 4 Year MEC Exam Weight	WTMEC4YR


# Adding gloria's for weight variable: SDDSRVYR and other clock and APC things if needed 

data_nhanes_gloria <- read.csv(here("big_data/NHANES/Gloria_preprocessed/Data-3/Core_Dataset_Aim2.csv"))

data_nhanes <- data_nhanes %>% 
  mutate(SEQN = as.character(BaseID)) %>% 
  left_join(data_nhanes_gloria %>% 
              rename(race_decoded = race) %>% 
              mutate(age = as.numeric(age)), 
            by = c("SEQN", "age")) %>% 
  mutate(age = as.numeric(age))

# add more

data_nhanes <- data_nhanes %>% 
  mutate(age_group = as.factor( 
                            cut(
                            age,
                            breaks = c(17, 29, 39, 49, 59, 69, Inf),
                            labels = c("18-29", "30-39", "40-49", "50-59", "60-69", "70+"),
                            levels = c("18-29", "30-39", "40-49", "50-59", "60-69", "70+"),
                            right = TRUE
                          )),
         health_cat = factor(srh, 
                        levels = 1:5,
                        labels = c("Poor", "Fair", "Good", "Very Good", "Excellent")))


```

```{r}

# more new columns to enable APC
data_nhanes <- data_nhanes %>% 
  mutate(period_cut_6 = as.factor(cut(data_nhanes$year, 6)),
    period_cut_10 = as.factor(cut(data_nhanes$year, 10)),
    period_cut_12 = as.factor(cut(data_nhanes$year, 12)),
    period_groups = as.factor(cut(data_nhanes$year, 12)),
    period_10yr = as.factor(
                            cut(
                            year,
                            breaks = c(1973, 1982, 1990, 1998, 2006, 2014, Inf),
                            labels = c("1974-1982", "1982-1990", "1990-1998", 
                                       "1998-2006", "2006-2014", "2014-2022"),
                            right = TRUE
                            )
                          ),
    period_decade = as.factor(
                            cut(
                            year,
                            breaks = c(1973, 1979, 1989, 1999, 2009, 2019, Inf),
                            labels = c("1974-1979", "1980-1989", "1990-1999",
                                       "2000-2009", "2010-2019", "2020-2024"),
                            right = TRUE
                            )
                          ),
    age_group = as.factor( 
                            cut(
                            age,
                            breaks = c(17, 29, 39, 49, 59, 69, Inf),
                            labels = c("18-29", "30-39", "40-49", "50-59", "60-69", "70+"),
                            right = TRUE
                          )),
    age_groups = as.factor( 
                            cut(
                            age,
                            breaks = c(17, 29, 39, 49, 59, 69, Inf),
                            labels = c("18-29", "30-39", "40-49", "50-59", "60-69", "70+"),
                            right = TRUE
                          )),
    age_group_small = as.factor( 
                            cut(
                              age,
                              breaks = c(seq(15, 75, by = 5), Inf),  # Define breaks up to 75 and include Inf for the last group
                              labels = c("16-20", "21-25", "26-30", "31-35", "36-40", "41-45", "46-50", "51-55", "56-60", "61-65", "66-70", "71-75", "76+"),
                              right = FALSE  # Makes intervals left-closed, i.e., [x, y)
                            )
                          )
                          ,
    generation = factor(
      case_when(
        cohort >= 1901 & cohort <= 1927 ~ "Greatest (1901-1927)",
        cohort >= 1928 & cohort <= 1945 ~ "Silent (1928-1945)",
        cohort >= 1946 & cohort <= 1964 ~ "Boomers (1946-1964)",
        cohort >= 1965 & cohort <= 1980 ~ "Gen X (1965-1980)",
        cohort >= 1981 & cohort <= 1996 ~ "Millennials (1981-1996)",
        cohort >= 1997 & cohort <= 2012 ~ "Gen Z (1997-2012)",
        TRUE ~ "Other"
      ),
      levels = c(
        "Greatest (1901-1927)",
        "Silent (1928-1945)",
        "Boomers (1946-1964)",
        "Gen X (1965-1980)",
        "Millennials (1981-1996)",
        "Gen Z (1997-2012)"#,
     #   "Other"
      )
    ),
    generation_two_sections = factor(
      case_when(
        generation == "Greatest (1901-1927)" & cohort <= 1914 ~ "Greatest Early (1901-1914)",
        generation == "Greatest (1901-1927)" & cohort > 1914 ~ "Greatest Late (1915-1927)",
        generation == "Silent (1928-1945)" & cohort <= 1936 ~ "Silent Early (1928-1936)",
        generation == "Silent (1928-1945)" & cohort > 1936 ~ "Silent Late (1937-1945)",
        generation == "Boomers (1946-1964)" & cohort <= 1955 ~ "Boomers Early (1946-1955)",
        generation == "Boomers (1946-1964)" & cohort > 1955 ~ "Boomers Late (1956-1964)",
        generation == "Gen X (1965-1980)" & cohort <= 1972 ~ "Gen X Early (1965-1972)",
        generation == "Gen X (1965-1980)" & cohort > 1972 ~ "Gen X Late (1973-1980)",
        generation == "Millennials (1981-1996)" & cohort <= 1988 ~ "Millennials Early (1981-1988)",
        generation == "Millennials (1981-1996)" & cohort > 1988 ~ "Millennials Late (1989-1996)",
        generation == "Gen Z (1997-2012)" & cohort <= 2004 ~ "Gen Z Early (1997-2004)",
        generation == "Gen Z (1997-2012)" & cohort > 2004 ~ "Gen Z Late (2005-2012)",
        TRUE ~ "Other"
      ),
      levels = c(
        "Greatest Early (1901-1914)", "Greatest Late (1915-1927)",
        "Silent Early (1928-1936)", "Silent Late (1937-1945)",
        "Boomers Early (1946-1955)", "Boomers Late (1956-1964)",
        "Gen X Early (1965-1972)", "Gen X Late (1973-1980)",
        "Millennials Early (1981-1988)", "Millennials Late (1989-1996)",
        "Gen Z Early (1997-2004)", "Gen Z Late (2005-2012)"#,
     #   "Other"
      )
    ),
    generation_three_sections = factor(
      case_when(
        generation == "Greatest (1901-1927)" & cohort <= 1910 ~ "Greatest Early (1901-1910)",
        generation == "Greatest (1901-1927)" & cohort > 1910 & cohort <= 1918 ~ "Greatest Mid (1911-1918)",
        generation == "Greatest (1901-1927)" & cohort > 1918 ~ "Greatest Late (1919-1927)",
        generation == "Silent (1928-1945)" & cohort <= 1934 ~ "Silent Early (1928-1934)",
        generation == "Silent (1928-1945)" & cohort > 1934 & cohort <= 1940 ~ "Silent Mid (1935-1940)",
        generation == "Silent (1928-1945)" & cohort > 1940 ~ "Silent Late (1941-1945)",
        generation == "Boomers (1946-1964)" & cohort <= 1951 ~ "Boomers Early (1946-1951)",
        generation == "Boomers (1946-1964)" & cohort > 1951 & cohort <= 1958 ~ "Boomers Mid (1952-1958)",
        generation == "Boomers (1946-1964)" & cohort > 1958 ~ "Boomers Late (1959-1964)",
        generation == "Gen X (1965-1980)" & cohort <= 1970 ~ "Gen X Early (1965-1970)",
        generation == "Gen X (1965-1980)" & cohort > 1970 & cohort <= 1976 ~ "Gen X Mid (1971-1976)",
        generation == "Gen X (1965-1980)" & cohort > 1976 ~ "Gen X Late (1977-1980)",
        generation == "Millennials (1981-1996)" & cohort <= 1986 ~ "Millennials Early (1981-1986)",
        generation == "Millennials (1981-1996)" & cohort > 1986 & cohort <= 1992 ~ "Millennials Mid (1987-1992)",
        generation == "Millennials (1981-1996)" & cohort > 1992 ~ "Millennials Late / Gen Z (1993-2004)",
    #    generation == "Gen Z (1997-2012)" & cohort <= 2002 ~ "Gen Z Early (1997-2002)",
    #    generation == "Gen Z (1997-2012)" & cohort > 2002 & cohort <= 2008 ~ "Gen Z Mid (2003-2008)",
    #    generation == "Gen Z (1997-2012)" & cohort > 2008 ~ "Gen Z Late (2009-2012)",
        TRUE ~ "Other"
      ),
      levels = c(
        "Greatest Early (1901-1910)", "Greatest Mid (1911-1918)", "Greatest Late (1919-1927)",
        "Silent Early (1928-1934)", "Silent Mid (1935-1940)", "Silent Late (1941-1945)",
        "Boomers Early (1946-1951)", "Boomers Mid (1952-1958)", "Boomers Late (1959-1964)",
        "Gen X Early (1965-1970)", "Gen X Mid (1971-1976)", "Gen X Late (1977-1980)",
        "Millennials Early (1981-1986)", "Millennials Mid (1987-1992)", 
        "Millennials Late / Gen Z (1993-2004)"
        #"Millennials Late (1993-1996)",
      #  "Gen Z Early (1997-2002)", "Gen Z Mid (2003-2008)", "Gen Z Late (2009-2012)" #,
      #  "Other"
      )
    ))
  

```


# Survival Analysis (Without Weights)

```{r}

coxph_all_unweighted <- coxph(Surv(time=age_visit, time2=age_last, event=deceased)~srh, data=data_nhanes)
coxph_all_unweighted
coxph_all_unweighted$coefficients[1]

table(data_nhanes$year)

coxph_unweighted_2001 <- coxph(Surv(time=age_visit, time2=age_last, event=deceased)~srh, 
      data= data_nhanes %>% filter(year == 2001))
coxph_unweighted_2003 <- coxph(Surv(time=age_visit, time2=age_last, event=deceased)~srh, 
      data= data_nhanes %>% filter(year == 2003))
coxph_unweighted_2005 <- coxph(Surv(time=age_visit, time2=age_last, event=deceased)~srh, 
      data= data_nhanes %>% filter(year == 2005))
coxph_unweighted_2007 <- coxph(Surv(time=age_visit, time2=age_last, event=deceased)~srh, 
      data= data_nhanes %>% filter(year == 2007))
coxph_unweighted_2009 <- coxph(Surv(time=age_visit, time2=age_last, event=deceased)~srh, 
      data= data_nhanes %>% filter(year == 2009))
coxph_unweighted_2011 <- coxph(Surv(time=age_visit, time2=age_last, event=deceased)~srh, 
      data= data_nhanes %>% filter(year == 2011))
coxph_unweighted_2013 <- coxph(Surv(time=age_visit, time2=age_last, event=deceased)~srh, 
      data= data_nhanes %>% filter(year == 2013))
coxph_unweighted_2015 <- coxph(Surv(time=age_visit, time2=age_last, event=deceased)~srh, 
      data= data_nhanes %>% filter(year == 2015))
coxph_unweighted_2017 <- coxph(Surv(time=age_visit, time2=age_last, event=deceased)~srh, 
      data= data_nhanes %>% filter(year == 2017))

coxph_unweighted_2001
coxph_unweighted_2003
coxph_unweighted_2005
coxph_unweighted_2007
coxph_unweighted_2009
coxph_unweighted_2011
coxph_unweighted_2013
coxph_unweighted_2015
coxph_unweighted_2017

coef_over_time <- c(coxph_unweighted_2001$coefficients,
coxph_unweighted_2003$coefficients,
coxph_unweighted_2005$coefficients,
coxph_unweighted_2007$coefficients,
coxph_unweighted_2009$coefficients,
coxph_unweighted_2011$coefficients,
coxph_unweighted_2013$coefficients,
coxph_unweighted_2015$coefficients,
coxph_unweighted_2017$coefficients)

coef_over_time

# They do increase

```

```{r}

table(data_nhanes$year)
table(data_nhanes$cohort_4yr)
dim(data_nhanes %>% filter(cohort_4yr == 1939))

coxph_unweighted_2001 <- coxph(Surv(time=age_visit, time2=age_last, event=deceased)~srh, 
      data= data_nhanes %>% filter(year == 2001))
coxph_unweighted_2003 <- coxph(Surv(time=age_visit, time2=age_last, event=deceased)~srh, 
      data= data_nhanes %>% filter(year == 2003))
coxph_unweighted_2005 <- coxph(Surv(time=age_visit, time2=age_last, event=deceased)~srh, 
      data= data_nhanes %>% filter(year == 2005))
coxph_unweighted_2007 <- coxph(Surv(time=age_visit, time2=age_last, event=deceased)~srh, 
      data= data_nhanes %>% filter(year == 2007))
coxph_unweighted_2009 <- coxph(Surv(time=age_visit, time2=age_last, event=deceased)~srh, 
      data= data_nhanes %>% filter(year == 2009))
coxph_unweighted_2011 <- coxph(Surv(time=age_visit, time2=age_last, event=deceased)~srh, 
      data= data_nhanes %>% filter(year == 2011))
coxph_unweighted_2013 <- coxph(Surv(time=age_visit, time2=age_last, event=deceased)~srh, 
      data= data_nhanes %>% filter(year == 2013))
coxph_unweighted_2015 <- coxph(Surv(time=age_visit, time2=age_last, event=deceased)~srh, 
      data= data_nhanes %>% filter(year == 2015))
coxph_unweighted_2017 <- coxph(Surv(time=age_visit, time2=age_last, event=deceased)~srh, 
      data= data_nhanes %>% filter(year == 2017))

coxph_unweighted_2001
coxph_unweighted_2003
coxph_unweighted_2005
coxph_unweighted_2007
coxph_unweighted_2009
coxph_unweighted_2011
coxph_unweighted_2013
coxph_unweighted_2015
coxph_unweighted_2017

coef_over_time <- c(coxph_unweighted_2001$coefficients,
coxph_unweighted_2003$coefficients,
coxph_unweighted_2005$coefficients,
coxph_unweighted_2007$coefficients,
coxph_unweighted_2009$coefficients,
coxph_unweighted_2011$coefficients,
coxph_unweighted_2013$coefficients,
coxph_unweighted_2015$coefficients,
coxph_unweighted_2017$coefficients)

coef_over_time

```


# Survival Analysis

## All combined 
```{r}

coxph(Surv(time=age_visit, time2=age_last, event=deceased)~srh, data=data_nhanes)
coxph_all_unweighted

```

# By Year

```{r}
# Fit the Cox PH model within each year-group and extract the coefficient
coef_over_time <- data_nhanes %>%
  group_by(year) %>%
  # Use group_modify to apply a function that fits a coxph model 
  #    to each year's subset of the data
  group_modify(~ {
    # Fit the Cox model
    cox_model <- coxph(
      Surv(time = age_visit, time2 = age_last, event = deceased) ~ srh, 
      data = .x
    )
    # 4. Extract the coefficient for srh
    # Get a summary of the model
    cox_summary <- summary(cox_model)
    
    # 4. Extract key metrics from the summary
    #    The 'coefficients' matrix in cox_summary has columns: 
    #    coef, exp(coef), se(coef), z, Pr(>|z|)
    #    The 'conf.int' matrix has columns: exp(coef), exp(-coef), lower .95, upper .95
    tibble(
      coefficient_srh   = cox_summary$coefficients[1, "coef"],
      se_srh            = cox_summary$coefficients[1, "se(coef)"],
      z_value_srh       = cox_summary$coefficients[1, "z"],
      p_value_srh       = cox_summary$coefficients[1, "Pr(>|z|)"],
      hr_srh            = cox_summary$conf.int[1, "exp(coef)"],    # Hazard Ratio
      hr_lower_95_srh   = cox_summary$conf.int[1, "lower .95"],    # 95% CI lower bound
      hr_upper_95_srh   = cox_summary$conf.int[1, "upper .95"]     # 95% CI upper bound
    )
  }) %>%
  # 5. Ungroup to finish
  ungroup()

coef_over_time

coef_over_time %>% 
  ggplot(aes(x = year, y = coefficient_srh)) + 
  geom_point() +
  geom_line() +
  theme_minimal()

coef_over_time %>%
  filter(!(is.na(year))) %>% 
  ggplot(aes(x = factor(year), 
             y = coefficient_srh, 
             ymin = coefficient_srh - 1.96 * se_srh, 
             ymax = coefficient_srh + 1.96 * se_srh)) +
  
  geom_pointrange() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(
    x = "Survey Year",
    y = "Log Hazard Ratio (Coefficient ± 1.96*SE)",
    title = "Coefficient for SRH Across Years"
  ) +
  theme_minimal()


# Forest plot

# 1. Forest-plot style for HRs
coef_over_time %>%
  filter(!(is.na(year))) %>% 
  ggplot(aes(x = factor(year), 
             y = hr_srh, 
             ymin = hr_lower_95_srh, 
             ymax = hr_upper_95_srh)) +
  
  # Point + error bars
  geom_pointrange() +
  
  # Horizontal reference line at HR=1.0
  geom_hline(yintercept = 1, linetype = "dashed", color = "red") +
  
  # Axis labels, theme
  labs(
    x = "Survey Year",
    y = "Hazard Ratio (HR) [95% CI]",
    title = "Hazard Ratios for SRH Across Years"
  ) +
  coord_flip() +  # flip coordinates if you prefer a vertical forest plot
  theme_minimal()


# p-value plot
coef_over_time %>%
  filter(!(is.na(year))) %>% 
  ggplot(aes(x = factor(year), 
             y = -log10(p_value_srh))) +  # transform p-values for better scale
  geom_col() + 
  geom_hline(yintercept = -log10(0.05), 
             linetype = "dashed", 
             color = "red") +
  labs(
    x = "Survey Year",
    y = expression(-log[10](p)),
    title = "P-value for SRH Across Years"
  ) +
  theme_minimal()


```

## By cohort
```{r}
# By generation

coef_over_cohort <- data_nhanes %>%
  group_by(generation_two_sections) %>%
  # Use group_modify to apply a function that fits a coxph model 
  #    to each year's subset of the data
  group_modify(~ {
    # Fit the Cox model
    cox_model <- coxph(
      Surv(time = age_visit, time2 = age_last, event = deceased) ~ srh, 
      data = .x
    )
    # 4. Extract the coefficient for srh
    # Get a summary of the model
    cox_summary <- summary(cox_model)
    
    # 4. Extract key metrics from the summary
    #    The 'coefficients' matrix in cox_summary has columns: 
    #    coef, exp(coef), se(coef), z, Pr(>|z|)
    #    The 'conf.int' matrix has columns: exp(coef), exp(-coef), lower .95, upper .95
    tibble(
      coefficient_srh   = cox_summary$coefficients[1, "coef"],
      se_srh            = cox_summary$coefficients[1, "se(coef)"],
      z_value_srh       = cox_summary$coefficients[1, "z"],
      p_value_srh       = cox_summary$coefficients[1, "Pr(>|z|)"],
      hr_srh            = cox_summary$conf.int[1, "exp(coef)"],    # Hazard Ratio
      hr_lower_95_srh   = cox_summary$conf.int[1, "lower .95"],    # 95% CI lower bound
      hr_upper_95_srh   = cox_summary$conf.int[1, "upper .95"]     # 95% CI upper bound
    )
  }) %>%
  # 5. Ungroup to finish
  ungroup()

coef_over_cohort

coef_over_cohort %>% 
  ggplot(aes(x = generation_two_sections, y = coefficient_srh)) + 
  geom_point() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))


coef_over_cohort %>%
  filter(!(is.na(generation_two_sections))) %>% 
  filter(generation_two_sections != "Gen Z Early (1997-2004)") %>% 
  ggplot(aes(x = factor(generation_two_sections), 
             y = coefficient_srh, 
             ymin = coefficient_srh - 1.96 * se_srh, 
             ymax = coefficient_srh + 1.96 * se_srh)) +
  
  geom_pointrange() +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(
    x = "Cohort",
    y = "Log Hazard Ratio (Coefficient ± 1.96*SE)",
    title = "Coefficient for SRH for Diffrerent Generations"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

# Forest plot

# 1. Forest-plot style for HRs
coef_over_cohort %>%
  filter(!(is.na(generation_two_sections))) %>% 
  filter(generation_two_sections != "Gen Z Early (1997-2004)") %>% 
  ggplot(aes(x = factor(generation_two_sections), 
             y = hr_srh, 
             ymin = hr_lower_95_srh, 
             ymax = hr_upper_95_srh)) +
  
  # Point + error bars
  geom_pointrange() +
  
  # Horizontal reference line at HR=1.0
  geom_hline(yintercept = 1, linetype = "dashed", color = "red") +
  
  # Axis labels, theme
  labs(
    x = "Generation",
    y = "Hazard Ratio (HR) [95% CI]",
    title = "Hazard Ratios for SRH Across Cohorts"
  ) +
  coord_flip() +  # flip coordinates if you prefer a vertical forest plot
  theme_minimal()

# p-value plot
coef_over_cohort %>%
  filter(!(is.na(generation_two_sections))) %>% 
  filter(generation_two_sections != "Gen Z Early (1997-2004)") %>% 
  ggplot(aes(x = factor(generation_two_sections), 
             y = -log10(p_value_srh))) +  # transform p-values for better scale
  geom_col() + 
  geom_hline(yintercept = -log10(0.05), 
             linetype = "dashed", 
             color = "red") +
  labs(
    x = "Survey Year",
    y = expression(-log[10](p)),
    title = "P-value for SRH Across Cohorts"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))


```

## Year and cohort
```{r}
data_nhanes %>%
  group_by(year, generation_two_sections) %>%
  # Use group_modify to apply a function that fits a coxph model 
  #    to each year's subset of the data
  group_modify(~ {
    # Fit the Cox model
    cox_model <- coxph(
      Surv(time = age_visit, time2 = age_last, event = deceased) ~ srh, 
      data = .x
    )
    # 4. Extract the coefficient for srh
    # Get a summary of the model
    cox_summary <- summary(cox_model)
    
    # 4. Extract key metrics from the summary
    #    The 'coefficients' matrix in cox_summary has columns: 
    #    coef, exp(coef), se(coef), z, Pr(>|z|)
    #    The 'conf.int' matrix has columns: exp(coef), exp(-coef), lower .95, upper .95
    tibble(
      coefficient_srh   = cox_summary$coefficients[1, "coef"],
      se_srh            = cox_summary$coefficients[1, "se(coef)"],
      z_value_srh       = cox_summary$coefficients[1, "z"],
      p_value_srh       = cox_summary$coefficients[1, "Pr(>|z|)"],
      hr_srh            = cox_summary$conf.int[1, "exp(coef)"],    # Hazard Ratio
      hr_lower_95_srh   = cox_summary$conf.int[1, "lower .95"],    # 95% CI lower bound
      hr_upper_95_srh   = cox_summary$conf.int[1, "upper .95"]     # 95% CI upper bound
    )
  }) %>%
  # 5. Ungroup to finish
  ungroup() %>% 
  filter(coefficient_srh < 5) %>% 
  ggplot(aes(x = year, y = coefficient_srh)) +
  facet_wrap(~generation_two_sections) +
  geom_line()

```

