---
title: "APC Health Sandbox"
author: "Christine Lucille Kuryla"
date: "2024-09-28"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Main components
1. Pick some variables of interest
2. Explain what variables were picked
3. APC: Plots of various APC dimensions 
  * (Unpooled: Run regression for one time period)
4. APC: Additional plots of remaining APC dimensions 
  * (Unpooled: Run regression for another time period)
5. APC: Run a parsimonious regression of age period cohort variables 
  * (Unpooled: Interpret at least some of the coefficients)
6. APC: Interpret the results of the regression 
  * (Unpooled: Formally compare coefficients between time periods)
7. APC: Explain why the parsimonious model makes sense
  * Unpooled: Explain results 

# Extra ideas
* "secret weapon" (coefficent for each years) of "happy" (or w/e) as a predictor of "health"
* data missingness figure
* mixtures?!?

# Potential covariates
* specific health conditions -- but there are a lot!! maybe a faceted graph?

# Misc thoughts
* How do we incorporate adjusted age? 
  * Prospective age
    * life expectancy - current age
    * percent spent
    * # of years left
      * dichotomous if over/under 10/15 years left
    * # of percent left
* https://socialwork.columbia.edu/directory/julien-o-teitler
* Jim's idea about slope of IQR/diff over time and separating out by state/environmental exposure/etc
* Death's of Despair debunking
  * composition of age buckets
* Rai's observation of squiglyness of old age SRH decreasing at later survey years
* Apparently we can incorporate death data with GSS so figure out how to get that data - ask Greg

# To do
* Find some more potential covariates
* Read the two APC articles recommended
  * first
  * https://pubmed.ncbi.nlm.nih.gov/37032706/
* Read deaths of despair and debunking 

# Resources

Actual instructions
* https://www.publichealth.columbia.edu/research/population-health-methods/age-period-cohort-analysis
* https://www.pewresearch.org/decoded/2023/05/22/assessing-the-effects-of-generation-using-age-period-cohort-analysis/ 

Review
* https://scholar.harvard.edu/files/apc/files/analyzing_age-period-cohort_data-_a_review_and_critique1.pdf 

# More Data
* GSS: https://gssdataexplorer.norc.org/about 
  * here's one distilled thing to check out: https://gss.norc.org/content/dam/gss/get-documentation/pdf/other/R1%20Release%20Variables.pdf 
* berkeley thing
* HRS - https://hrs.isr.umich.edu/data-products 
* Life Expectancy 
  * https://www.macrotrends.net/global-metrics/countries/USA/united-states/life-expectancy
  * UN: https://population.un.org/wpp/Download/Standard/CSV/ 
* World Value Survey/European Value Survey to combine: note there are only 5 waves of WVS and like 7 of EVS
  * https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5420378/
* NIHS
  * https://www.cdc.gov/nchs/nhis/data-questionnaires-documentation.htm

# Background Research on Self-Rated Health

* Changes in Self-Rated Health Status by Demographic Characteristics among Adults, 2014-2017
  * * https://www.census.gov/library/working-papers/2024/demo/sehsd-wp2024-09.html
* Cultural values: can they explain self-reported health? (WVS and x)
  * https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5420378/#CR32


* 